development:
  adapter: postgresql
  encoding: unicode
  database: calendar_dev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: calendar_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: calendar_prod
  pool: 5
  username: postgres
  password:
